package main

import (
	"github.com/vsonline/mcp-server/config"
	"github.com/vsonline/mcp-server/models"
	tools_pools "github.com/vsonline/mcp-server/tools/pools"
	tools_netmon "github.com/vsonline/mcp-server/tools/netmon"
	tools_sas "github.com/vsonline/mcp-server/tools/sas"
	tools_plans "github.com/vsonline/mcp-server/tools/plans"
	tools_environments "github.com/vsonline/mcp-server/tools/environments"
	tools_heartbeat "github.com/vsonline/mcp-server/tools/heartbeat"
	tools_tokens "github.com/vsonline/mcp-server/tools/tokens"
	tools_prebuildsv "github.com/vsonline/mcp-server/tools/prebuildsv"
	tools_billing "github.com/vsonline/mcp-server/tools/billing"
	tools_prebuilds "github.com/vsonline/mcp-server/tools/prebuilds"
	tools_health "github.com/vsonline/mcp-server/tools/health"
	tools_vnetpooldefinitions "github.com/vsonline/mcp-server/tools/vnetpooldefinitions"
	tools_agents "github.com/vsonline/mcp-server/tools/agents"
	tools_agenttelemetry "github.com/vsonline/mcp-server/tools/agenttelemetry"
	tools_warmup "github.com/vsonline/mcp-server/tools/warmup"
	tools_locations "github.com/vsonline/mcp-server/tools/locations"
	tools_networksettings "github.com/vsonline/mcp-server/tools/networksettings"
	tools_tenant "github.com/vsonline/mcp-server/tools/tenant"
	tools_pool "github.com/vsonline/mcp-server/tools/pool"
	tools_tunnel "github.com/vsonline/mcp-server/tools/tunnel"
	tools_vm "github.com/vsonline/mcp-server/tools/vm"
	tools_secrets "github.com/vsonline/mcp-server/tools/secrets"
	tools_resources "github.com/vsonline/mcp-server/tools/resources"
	tools_configuration "github.com/vsonline/mcp-server/tools/configuration"
	tools_poolgroup "github.com/vsonline/mcp-server/tools/poolgroup"
	tools_privacy "github.com/vsonline/mcp-server/tools/privacy"
	tools_usersubscriptions "github.com/vsonline/mcp-server/tools/usersubscriptions"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_pools.CreateGet_api_v1_pools_defaultTool(cfg),
		tools_netmon.CreateGet_internal_netmon_correlationTool(cfg),
		tools_sas.CreateGet_api_v1_sasTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcereadbeginTool(cfg),
		tools_environments.CreateGet_api_v1_environments_environmentid_stateTool(cfg),
		tools_pools.CreatePost_api_v1_genevaactions_pools_change_resource_deletion_settingTool(cfg),
		tools_heartbeat.CreatePost_api_v1_heartbeatTool(cfg),
		tools_environments.CreateUpdateenvironmentrouteTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_resourcereadbeginTool(cfg),
		tools_tokens.CreatePut_api_v1_tokens_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_providernamespace_plans_resourcenameTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_resourcedeletionvalidateTool(cfg),
		tools_prebuildsv.CreatePost_api_v2_prebuilds_templates_updatemaxversionsTool(cfg),
		tools_billing.CreateGet_api_v1_genevaactions_billing_environmentidTool(cfg),
		tools_environments.CreateDelete_api_v1_genevaactions_environments_environmentidTool(cfg),
		tools_environments.CreateGet_api_v1_genevaactions_environments_environmentidTool(cfg),
		tools_environments.CreateDelete_api_v1_environments_environmentid_ports_portTool(cfg),
		tools_environments.CreatePut_api_v1_environments_environmentid_ports_portTool(cfg),
		tools_prebuilds.CreateGettemplateinforouteTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_writecodespacesTool(cfg),
		tools_plans.CreatePut_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcenameTool(cfg),
		tools_health.CreateGet_healthTool(cfg),
		tools_pools.CreatePost_api_v1_genevaactions_pools_targetTool(cfg),
		tools_vnetpooldefinitions.CreateDelete_api_v1_genevaactions_vnetpooldefinitionsTool(cfg),
		tools_vnetpooldefinitions.CreatePost_api_v1_genevaactions_vnetpooldefinitionsTool(cfg),
		tools_pools.CreatePost_api_v1_genevaactions_pools_poolcode_rotate_poolTool(cfg),
		tools_environments.CreateGet_api_v1_genevaactions_environments_storage_environmentidorfriendlyname_targetblobTool(cfg),
		tools_agents.CreateGet_api_v1_agents_familyTool(cfg),
		tools_plans.CreatePut_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcenameTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_writeenvironmentsTool(cfg),
		tools_environments.CreatePost_api_v1_environments_environmentid_exportTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_readdelegatesTool(cfg),
		tools_agenttelemetry.CreatePost_api_v1_agenttelemetryTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_readallcodespacesTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_readallenvironmentsTool(cfg),
		tools_environments.CreatePost_api_v1_environments_environmentid_shutdownTool(cfg),
		tools_tokens.CreatePost_api_v1_tokens_plans_planname_deleteallcodespacesTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_writeenvironmentsTool(cfg),
		tools_warmup.CreateGet_warmupTool(cfg),
		tools_environments.CreateGet_api_v1_environmentsTool(cfg),
		tools_environments.CreatePost_api_v1_environmentsTool(cfg),
		tools_environments.CreatePatch_api_v1_environments_environmentid_folderTool(cfg),
		tools_locations.CreateGet_api_v1_locations_locationTool(cfg),
		tools_environments.CreateGet_api_v1_environments_environmentid_archiveTool(cfg),
		tools_environments.CreatePost_api_v1_environments_environmentid_archiveTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_deleteallcodespacesTool(cfg),
		tools_locations.CreateGet_api_v1_locationsTool(cfg),
		tools_tokens.CreatePost_api_v1_tokens_plans_planname_writecodespacesTool(cfg),
		tools_plans.CreatePut_api_v1_subscriptions_subscriptionid_providers_microsoft_vsonline_plans_subscriptionlifecyclenotificationTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_readallcodespacesTool(cfg),
		tools_networksettings.CreatePut_api_v1_subscriptions_subscriptionid_providers_github_network_resourcetype_subscriptionlifecyclenotificationTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_providers_microsoft_codespaces_plans_resourcereadbeginTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_resourcepatchcompletedTool(cfg),
		tools_prebuildsv.CreatePost_api_v2_prebuilds_templatesTool(cfg),
		tools_tenant.CreateDelete_api_v1_tenant_tenantidTool(cfg),
		tools_tenant.CreateGet_api_v1_tenant_tenantidTool(cfg),
		tools_tenant.CreatePut_api_v1_tenant_tenantidTool(cfg),
		tools_tokens.CreatePost_api_v1_tokens_plans_planname_writedelegatesTool(cfg),
		tools_pool.CreatePut_api_v1_tenant_tenantid_pool_poolnameTool(cfg),
		tools_pool.CreateDelete_api_v1_tenant_tenantid_pool_poolnameTool(cfg),
		tools_pool.CreateGet_api_v1_tenant_tenantid_pool_poolnameTool(cfg),
		tools_pool.CreatePatch_api_v1_tenant_tenantid_pool_poolnameTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_resourcepatchcompletedTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_resourcedeletionvalidateTool(cfg),
		tools_tunnel.CreateGet_api_v1_tunnel_environmentid_portinfoTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcereadbeginTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_resourcecreationcompletedTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_resourcecreationcompletedTool(cfg),
		tools_vm.CreatePost_api_v1_tenant_tenantid_pool_poolname_vm_vmname_startTool(cfg),
		tools_prebuilds.CreatePost_api_v1_genevaactions_prebuilds_pools_createorupdatesettingsTool(cfg),
		tools_prebuildsv.CreatePost_api_v2_prebuilds_templates_templateid_updatestatusTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_writecodespacesTool(cfg),
		tools_prebuildsv.CreatePost_api_v2_prebuilds_deleteTool(cfg),
		tools_environments.CreatePut_api_v1_genevaactions_environments_environmentid_archiveTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_readallenvironmentsTool(cfg),
		tools_vm.CreateGet_api_v1_tenant_tenantid_pool_poolname_vmTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcename_resourcedeletionvalidateTool(cfg),
		tools_prebuilds.CreatePost_api_v1_genevaactions_prebuilds_pools_deleteTool(cfg),
		tools_environments.CreatePost_api_v1_genevaactions_environments_environmentid_upload_running_vm_logsTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcename_resourcereadbeginTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_deleteallenvironmentsTool(cfg),
		tools_environments.CreatePost_api_v1_environments_environmentid_notifyTool(cfg),
		tools_environments.CreatePatch_api_v1_environments_environmentid_restoreTool(cfg),
		tools_tokens.CreatePost_api_v1_tokens_plans_planname_readallcodespacesTool(cfg),
		tools_billing.CreatePost_api_v1_genevaactions_billing_environmentid_state_changesTool(cfg),
		tools_billing.CreateGet_api_v1_genevaactions_billing_environmentid_state_changesTool(cfg),
		tools_secrets.CreateDelete_api_v1_secrets_secretidTool(cfg),
		tools_secrets.CreatePut_api_v1_secrets_secretidTool(cfg),
		tools_agenttelemetry.CreatePost_api_v1_agenttelemetry_standaloneTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_deleteallenvironmentsTool(cfg),
		tools_environments.CreatePut_api_v1_genevaactions_environments_environmentid_shutdownTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroup_providers_microsoft_codespaces_plans_resourcename_deletedelegatesTool(cfg),
		tools_resources.CreatePost_api_v1_genevaactions_resources_resourceid_under_investigationTool(cfg),
		tools_billing.CreatePost_api_v1_genevaactions_billing_resendTool(cfg),
		tools_plans.CreatePut_api_v1_subscriptions_subscriptionid_providers_microsoft_codespaces_plans_subscriptionlifecyclenotificationTool(cfg),
		tools_prebuilds.CreatePost_api_v1_prebuilds_pools_poolid_instancesTool(cfg),
		tools_prebuilds.CreatePut_api_v1_prebuilds_pools_poolid_instancesTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_resourcecreationvalidateTool(cfg),
		tools_configuration.CreateDelete_api_v1_genevaactions_configuration_target_keyTool(cfg),
		tools_configuration.CreateGet_api_v1_genevaactions_configuration_target_keyTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_readdelegatesTool(cfg),
		tools_secrets.CreateGet_api_v1_secretsTool(cfg),
		tools_secrets.CreatePost_api_v1_secretsTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcename_resourcecreationcompletedTool(cfg),
		tools_poolgroup.CreatePatch_api_v1_tenant_tenantid_poolgroup_poolgroupnameTool(cfg),
		tools_poolgroup.CreatePut_api_v1_tenant_tenantid_poolgroup_poolgroupnameTool(cfg),
		tools_poolgroup.CreateDelete_api_v1_tenant_tenantid_poolgroup_poolgroupnameTool(cfg),
		tools_poolgroup.CreateGet_api_v1_tenant_tenantid_poolgroup_poolgroupnameTool(cfg),
		tools_prebuildsv.CreateGetprebuildreadinessskusrouteTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_writedelegatesTool(cfg),
		tools_configuration.CreatePost_api_v1_genevaactions_configuration_targetTool(cfg),
		tools_environments.CreatePost_api_v1_environments_environmentid_startTool(cfg),
		tools_vm.CreateDelete_api_v1_tenant_tenantid_pool_poolname_vm_vmnameTool(cfg),
		tools_vm.CreateGet_api_v1_tenant_tenantid_pool_poolname_vm_vmnameTool(cfg),
		tools_vm.CreatePut_api_v1_tenant_tenantid_pool_poolname_vm_vmnameTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcereadbeginTool(cfg),
		tools_environments.CreatePut_api_v1_environments_environmentid_secretsTool(cfg),
		tools_vm.CreatePost_api_v1_tenant_tenantid_pool_poolname_vm_vmname_stopTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcename_resourcepatchcompletedTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcename_resourcedeletioncompletedTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcename_resourcecreationvalidateTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_resourcereadbeginTool(cfg),
		tools_environments.CreateGetenvironmentrouteTool(cfg),
		tools_environments.CreatePatch_api_v1_environments_environmentidTool(cfg),
		tools_environments.CreateDelete_api_v1_environments_environmentidTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_resourcepatchvalidateTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroup_providers_microsoft_vsonline_plans_resourcename_deletedelegatesTool(cfg),
		tools_prebuildsv.CreateDelete_api_v2_prebuilds_repository_repoid_branch_branchnameTool(cfg),
		tools_privacy.CreatePost_api_v1_genevaactions_privacy_refresh_profile_telemetry_propertiesTool(cfg),
		tools_environments.CreateGet_api_v1_environments_environmentid_heartbeattokenTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_resourcecreationvalidateTool(cfg),
		tools_networksettings.CreateDelete_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcenameTool(cfg),
		tools_networksettings.CreatePatch_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcenameTool(cfg),
		tools_networksettings.CreatePut_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcenameTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_writedelegatesTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_providers_microsoft_vsonline_plans_resourcereadbeginTool(cfg),
		tools_usersubscriptions.CreateDelete_api_v1_usersubscriptionsTool(cfg),
		tools_usersubscriptions.CreatePost_api_v1_usersubscriptionsTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_vsonline_plans_resourcename_deleteallcodespacesTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_github_network_resourcetype_resourcename_resourcepatchvalidateTool(cfg),
		tools_environments.CreateGet_api_v1_environments_environmentid_updatesTool(cfg),
		tools_networksettings.CreatePost_api_v1_subscriptions_subscriptionid_providers_github_network_resourcetype_resourcereadbeginTool(cfg),
		tools_plans.CreatePost_api_v1_subscriptions_subscriptionid_resourcegroups_resourcegroup_providers_microsoft_codespaces_plans_resourcename_resourcepatchvalidateTool(cfg),
	}
}
